# Generated by Django 5.1.15 on 2026-08-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Homepage'), ('menu', 'Menu'), ('about', 'About'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.CharField(blank=True, max_length=500)),
                ('twitter_image', models.CharField(blank=True, max_length=500)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('structured_data', models.TextField(blank=True, help_text='Raw JSON-LD, optional')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
    ]
