# Generated by Django 5.1.15 on 2026-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seosetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='page_key',
            field=models.CharField(choices=[('home', 'Homepage'), ('menu', 'Menu'), ('about', 'About'), ('contact', 'Contact'), ('gallery', 'Gallery')], max_length=20, unique=True),
        ),
    ]
