# Generated by Django 5.1.15 on 2026-08-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_seosetting_page_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
