# Generated by Django 5.1.15 on 2026-08-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_blogpost_options_blogpost_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seosetting',
            name='page_key',
            field=models.CharField(choices=[('home', 'Homepage'), ('menu', 'Menu'), ('about', 'About'), ('contact', 'Contact'), ('gallery', 'Gallery'), ('blog', 'Blog')], max_length=20, unique=True),
        ),
    ]
