# Generated by Django 5.1.15 on 2026-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_seosetting_page_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
