# Generated by Django 5.1.15 on 2026-08-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=150000, help_text='Flat delivery fee in Toman'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Order subtotal (Toman) at or above which delivery is free. 0 disables free delivery.'),
        ),
    ]
