# Generated by Django 5.1.15 on 2026-08-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_sitesettings_delivery_fee_and_more'),
        ('core', '0002_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('homepage_hero', 'homepage_hero'), ('homepage_about_teaser', 'homepage_about_teaser'), ('homepage_signature_dish', 'homepage_signature_dish'), ('about_hero', 'about_hero'), ('about_interior', 'about_interior'), ('about_chef', 'about_chef'), ('about_party', 'about_party'), ('about_plate', 'about_plate'), ('about_strength_hygienic', 'about_strength_hygienic'), ('about_strength_fresh', 'about_strength_fresh'), ('about_strength_chefs', 'about_strength_chefs'), ('about_strength_events', 'about_strength_events'), ('about_prefooter_1', 'about_prefooter_1'), ('about_prefooter_2', 'about_prefooter_2'), ('about_prefooter_3', 'about_prefooter_3'), ('about_prefooter_4', 'about_prefooter_4'), ('about_avatar_1', 'about_avatar_1'), ('about_avatar_2', 'about_avatar_2'), ('about_avatar_3', 'about_avatar_3'), ('booking_visual', 'booking_visual'), ('reservation_banner_bg', 'reservation_banner_bg')], max_length=50, unique=True)),
                ('group', models.CharField(choices=[('homepage', 'صفحه اصلی'), ('about', 'درباره ما'), ('booking', 'رزرو میز'), ('global', 'عمومی')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_slots', to='core.media')),
            ],
            options={
                'ordering': ['group', 'slug'],
            },
        ),
    ]
