# Generated by Django 5.1.15 on 2026-08-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('desserts', 'Desserts'), ('drinks', 'Drinks'), ('specials', 'Specials')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500)),
                ('plate_image', models.CharField(blank=True, max_length=500)),
                ('anatomy_image', models.CharField(blank=True, max_length=500)),
                ('process_image', models.CharField(blank=True, max_length=500)),
                ('prep_time', models.CharField(blank=True, max_length=50)),
                ('calories', models.CharField(blank=True, max_length=50)),
                ('spicy_level', models.CharField(blank=True, max_length=50)),
                ('allergens', models.CharField(blank=True, max_length=200)),
                ('vegan', models.CharField(blank=True, max_length=100)),
                ('taste_spiciness', models.PositiveSmallIntegerField(default=0)),
                ('taste_sweetness', models.PositiveSmallIntegerField(default=0)),
                ('taste_acidity', models.PositiveSmallIntegerField(default=0)),
                ('taste_richness', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('pairings', models.ManyToManyField(related_name='paired_by', through='menu.DishPairing', to='menu.menuitem')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='menu.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='dishpairing',
            name='main_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_links', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='dishpairing',
            name='paired_dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paired_dish_links', to='menu.menuitem'),
        ),
        migrations.CreateModel(
            name='DishHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.CharField(max_length=10)),
                ('left', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='menu.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DishGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500)),
                ('alt', models.CharField(max_length=200)),
                ('css_class', models.CharField(blank=True, max_length=100)),
                ('hover_x', models.IntegerField(default=0)),
                ('hover_y', models.IntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='menu.menuitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='menu_menuit_categor_58e9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['slug'], name='menu_menuit_slug_c22fc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishpairing',
            unique_together={('main_dish', 'paired_dish')},
        ),
    ]
